import {Geist, Geist_Mono, Inter, Noticia_Text, Poppins} from 'next/font/google'
import '../globals.css'

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// })

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// })

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})

const noticiaText = Noticia_Text({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-noticia-text',
})

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800'],
  variable: '--font-poppins',
})

// import type {Metadata} from 'next'

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

type Props = {
  children: React.ReactNode
}

export default function RootLayout({children}: Props) {
  return (
    <html lang="es" className={`${noticiaText.variable} ${poppins.variable} antialiased`}>
      <body>{children}</body>
    </html>
  )
}
